// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9uDYb9ZennftY3Ii_4KcebIXyg14TIYA',
    appId: '1:54820462772:web:892709e9e1488e645f77e1',
    messagingSenderId: '54820462772',
    projectId: 'rickandmortyapp-8e2fb',
    authDomain: 'rickandmortyapp-8e2fb.firebaseapp.com',
    storageBucket: 'rickandmortyapp-8e2fb.firebasestorage.app',
    measurementId: 'G-R6NLPXDLCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6dSTCCtJxUK3BNE6FN3XR2pn09Q-69s',
    appId: '1:54820462772:android:0c4068f02f2a81ed5f77e1',
    messagingSenderId: '54820462772',
    projectId: 'rickandmortyapp-8e2fb',
    storageBucket: 'rickandmortyapp-8e2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo-Tc8uVwu_LKLpOkXJ6GfU2SdvJayZlQ',
    appId: '1:54820462772:ios:24015e0206c65f615f77e1',
    messagingSenderId: '54820462772',
    projectId: 'rickandmortyapp-8e2fb',
    storageBucket: 'rickandmortyapp-8e2fb.firebasestorage.app',
    iosBundleId: 'com.example.rickandmortyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo-Tc8uVwu_LKLpOkXJ6GfU2SdvJayZlQ',
    appId: '1:54820462772:ios:24015e0206c65f615f77e1',
    messagingSenderId: '54820462772',
    projectId: 'rickandmortyapp-8e2fb',
    storageBucket: 'rickandmortyapp-8e2fb.firebasestorage.app',
    iosBundleId: 'com.example.rickandmortyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9uDYb9ZennftY3Ii_4KcebIXyg14TIYA',
    appId: '1:54820462772:web:f2a924e6d9f16a9f5f77e1',
    messagingSenderId: '54820462772',
    projectId: 'rickandmortyapp-8e2fb',
    authDomain: 'rickandmortyapp-8e2fb.firebaseapp.com',
    storageBucket: 'rickandmortyapp-8e2fb.firebasestorage.app',
    measurementId: 'G-26617C8PY7',
  );
}
